# base documental
spring:
  data:
    mongodb:
      uri: mongodb://capo:eyra@127.0.0.1:27018/futbol?authSource=admin
      database: local

logging:
  level:
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
